include:
  - component: $CI_SERVER_FQDN/ksoft/creatures/forge@0.20.0-dev.3
  - component: $CI_SERVER_FQDN/ksoft/creatures/linear@0.20.0-dev.3
  - component: $CI_SERVER_FQDN/ksoft/creatures/agents@0.20.0-dev.3
  - component: $CI_SERVER_FQDN/ksoft/creatures/rust@0.20.0-dev.3
    inputs:
      threshold: "20"
      bins: "insights insights_server"
      cargo-flags: "--no-default-features"
  - component: $CI_SERVER_FQDN/ksoft/creatures/github@0.20.0-dev.3

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_TAG
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
