#!/usr/bin/env bash
# insights shell bootstrap — generated by `insights setup`
# Edit freely; re-run `insights setup` to regenerate.

if command -v insights >/dev/null 2>&1; then
  export INSIGHTS_HOME="${INSIGHTS_HOME:-$HOME/.local/share/insights}"

  # Shell completions (if supported)
  if insights completions bash >/dev/null 2>&1; then
    eval "$(insights completions "${INSIGHTS_SHELL:-${SHELL##*/}}")"
  fi
fi
